// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/

/**
 *
 */
public class Admin_Permission extends Permission {
    /**
     *
     */
    public void indexSubmission() {
    }

    /**
     *
     */
    public void indexBucket() {
    }

    /**
     *
     */
    public void indexComments() {
    }

    /**
     *
     */
    public void indexUsers() {
    }
}
