// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/

/**
 *
 */
public class CommonVote {
    /**
     *
     */
    public int user_id;
    /**
     *
     */
    public int comment_id;
    /**
     *
     */
    public VoteType type;
    /**
     *
     */
    public Time created_at;
    /**
     *
     */
    public Time edited_at;

    /**
     * @param request
     */
    public void upVote(Request request) {
    }

    /**
     * @param request
     */
    public void downVote(Request request) {
    }
}
