// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/

/**
 *
 */
public class Comment {
    /**
     *
     */
    public int id;
    /**
     *
     */
    public int submission_id;
    /**
     *
     */
    public int user_id;
    /**
     *
     */
    public int parent_id;
    /**
     *
     */
    public int bucket_id;
    /**
     *
     */
    public int level;
    /**
     *
     */
    public int upvotes = 1;
    /**
     *
     */
    public int downvotes = 0;
    /**
     *
     */
    public String body;
    /**
     *
     */
    public Time created_at;
    /**
     *
     */
    public Time edited_at;
    /**
     *
     */
    public Time approved_at;

    /**
     * @param request
     * @param submission_id
     */
    public void store(Request request, int submission_id) {
    }

    /**
     * @param submission_id
     */
    public void index(int submission_id) {
    }

    /**
     * @param user_id
     * @param comment_id
     */
    public void firstVote(int user_id, int comment_id) {
    }

    /**
     * @param comment_id
     */
    public void destroy(int comment_id) {
    }

    /**
     * @param comment_id
     */
    public void patch(int comment_id) {
    }
};
