// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/

/**
 *
 */
public class Moderator_Permission extends Permission {
    /**
     * @param request
     */
    public void indexMods(Request request) {
    }

    /**
     * @param request
     */
    public void approveSubmssions(Request request) {
    }

    /**
     * @param request
     */
    public void disapproveSubmissions(Request request) {
    }

    /**
     * @param request
     */
    public void approveComment(Request request) {
    }

    /**
     * @param request
     */
    public void disapproveComment(Request request) {
    }

    /**
     * @param request
     */
    public void store(Request request) {
    }

    /**
     * @param request
     */
    public void destroy(Request request) {
    }
}
