// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/

/**
 *
 */
public class Role {
    /**
     *
     */
    public int user_id;
    /**
     *
     */
    public int bucket_id;
    /**
     *
     */
    public UserRole role;
    /**
     *
     */
    public Permission permission;

    /**
     * @param request
     */
    public void store(Request request) {
    }
}
