// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/

/**
 *
 */
public class Time {
    /**
     *
     */
    public int month;
    /**
     *
     */
    public int day;
    /**
     *
     */
    public int year;
    /**
     *
     */
    public int hour;
    /**
     *
     */
    public int minute;
    /**
     *
     */
    public int second;
}
