// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

import java.util.Scanner;

/************************************************************/

/**
 *
 */
public class User {
    /**
     *
     */
    public int id;
    /**
     *
     */
    public String username;
    /**
     *
     */
    public String name;
    /**
     *
     */
    public String website;
    /**
     *
     */
    public String bio;
    /**
     *
     */
    public String email;
    /**
     *
     */
    public String password;
    /**
     *
     */
    public boolean verified = false;
    /**
     *
     */
    public Time created_at;
    /**
     *
     */
    public Time edited_at;
    /**
     *
     */
    public int age;
    /**
     *
     */
    public Role role;

    /**
     *
     */
    public static void store() {
        Scanner s = new Scanner(System.in);
        System.out.println("Enter User ID");
        int u_id = s.nextInt();
        System.out.println("Enter UserName");
        String u_username = s.next();
        System.out.println("Enter Your Name");
        String u_name = s.next();

        boolean user_exist = Main.userArray.stream().anyMatch(b -> b.getId() == u_id);


        if (user_exist == false) {
            User u = new User();
            u.setId(u_id);
            u.setName(u_name);
            u.setUsername(u_username);
            Main.userArray.add(u);
        } else {
            System.out.println("User already exists.");
        }
    }

    /**
     *
     */
    public static void show() {
        Main.userArray.stream().forEach(s -> System.out.println(s.toString() + System.lineSeparator()));
    }

    /**
     * @return the id
     */
    public int getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the website
     */
    public String getWebsite() {
        return website;
    }

    /**
     * @param website the website to set
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * @return the bio
     */
    public String getBio() {
        return bio;
    }

    /**
     * @param bio the bio to set
     */
    public void setBio(String bio) {
        this.bio = bio;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the password
     */
    public String getPassword() {
        return password;
    }

    /**
     * @param password the password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the verified
     */
    public boolean isVerified() {
        return verified;
    }

    /**
     * @param verified the verified to set
     */
    public void setVerified(boolean verified) {
        this.verified = verified;
    }

    /**
     * @return the created_at
     */
    public Time getCreated_at() {
        return created_at;
    }

    /**
     * @param created_at the created_at to set
     */
    public void setCreated_at(Time created_at) {
        this.created_at = created_at;
    }

    /**
     * @return the edited_at
     */
    public Time getEdited_at() {
        return edited_at;
    }

    /**
     * @param edited_at the edited_at to set
     */
    public void setEdited_at(Time edited_at) {
        this.edited_at = edited_at;
    }

    /**
     * @return the age
     */
    public int getAge() {
        return age;
    }

    /**
     * @param age the age to set
     */
    public void setAge(int age) {
        this.age = age;
    }

    /**
     * @return the role
     */
    public Role getRole() {
        return role;
    }

    /**
     * @param role the role to set
     */
    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * @param username
     */
    public void showSubmission(String username) {
    }

    /**
     * @return
     */
    @Override
    public String toString() {
        return "Id: " + this.id + System.lineSeparator() + "UserName: " + this.username + System.lineSeparator() + "Name: " + this.name;
    }

    /**
     * @param username
     */
    public void showComments(String username) {
    }

    /**
     * @param request
     */
    public void submissions(Request request) {
    }

    /**
     * @param request
     */
    public void upVotedSubmissions(Request request) {
    }

    /**
     * @param request
     */
    public void downVotedSubmissions(Request request) {
    }

    /**
     * @param request
     */
    public void comments(Request request) {
    }

    /**
     * @param user_id
     */
    public void removeAllUserData(int user_id) {
    }

    /**
     *
     */
    public void isAdministrator() {
    }

    /**
     * @param request
     */
    public void profile(Request request) {
    }

    /**
     * @param request
     */
    public void password(Request request) {
    }
}
