// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package COEN;

/************************************************************/

/**
 *
 */
public class Vote {
    /**
     *
     */
    public int user_id;
    /**
     *
     */
    public int submission_id;
    /**
     *
     */
    public Time created_at;
    /**
     *
     */
    public Time edited_at;
    private VoteType upvote;
    /**
     *
     */
    public VoteType type = upvote;

    /**
     *
     */
    public static void upVote(int id) {
        boolean sub_exists = Main.subArray.stream().anyMatch(b -> b.getId() == id);

        if (sub_exists == true) {
            Submission ss = Main.subArray.stream().filter(s -> id == s.getId()).findFirst().orElse(null);
            ss.setUpvotes(ss.getUpvotes() + 1);
        } else {
            System.out.println("Submission doesn't exist. Create one first.");
        }
    }

    /**
     *
     */
    public static void downVote(int id) {
        boolean sub_exists = Main.subArray.stream().anyMatch(b -> b.getId() == id);

        if (sub_exists == true) {
            Submission ss = Main.subArray.stream().filter(s -> id == s.getId()).findFirst().orElse(null);
            ss.setDownvotes(ss.getDownvotes() + 1);
        } else {
            System.out.println("Submission doesn't exist. Create one first.");
        }
    }
}
